### ISSUE TITLE
Cannot make a WebPayment request

### ISSUE THREAD

**Issue by MenWhoRust** [PayGate/sample-code-csharp#8]
When trying to make a WebPayment request I receive the following exception

```
The HTTP request was forbidden with client authentication scheme 'Anonymous'.
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at PayHost.PayHOST.SinglePayment(SinglePaymentRequest1 request)
   at PayHost.PayHOSTClient.PayHost.PayHOST.SinglePayment(SinglePaymentRequest1 request) in C:\Users\prdec\AppData\Local\Temp\Temporary ASP.NET Files\vs\931bddb1\4c1aff62\App_WebReferences.vcmonaly.0.cs:line 7394
   at ASP._Page_Payhost_singlePayment_webPayment_index_cshtml.Execute() in C:\Users\prdec\Downloads\sample-code-csharp-master\WebSite1\Payhost\singlePayment\webPayment\index.cshtml:line 73
```

I have not made any changes to [this file](https://github.com/PayGate/sample-code-csharp/blob/9511cd5463b9ff6af37dfa427e8d20f424458a62/WebSite1/PayHost/singlePayment/webPayment/index.cshtml).

Below is the content of the WebPaymentRequestType
```
<WebPaymentRequestType xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <Account xmlns="http://www.paygate.co.za/PayHOST">
    <PayGateId>10011072130</PayGateId>
    <Password>test</Password>
  </Account>
  <Customer xmlns="http://www.paygate.co.za/PayHOST">
    <Title>Mr</Title>
    <FirstName>PayGate</FirstName>
    <LastName>Test</LastName>
    <Email>itsupport@paygate.co.za</Email>
    <Address>
      <AddressLine />
      <AddressLine />
      <AddressLine />
      <Country>ZAF</Country>
    </Address>
  </Customer>
  <PaymentType xmlns="http://www.paygate.co.za/PayHOST">
    <Method>CC</Method>
  </PaymentType>
  <Redirect xmlns="http://www.paygate.co.za/PayHOST">
    <NotifyUrl>http://localhost:57076/Payhost/notify.cshtml</NotifyUrl>
    <ReturnUrl>http://localhost:57076/Payhost/result.cshtml</ReturnUrl>
  </Redirect>
  <Order xmlns="http://www.paygate.co.za/PayHOST">
    <MerchantOrderId>pgtest_20210920152714</MerchantOrderId>
    <Currency>ZAR</Currency>
    <Amount>329900</Amount>
    <BillingDetails>
      <Customer>
        <Title>Mr</Title>
        <FirstName>PayGate</FirstName>
        <LastName>Test</LastName>
        <Email>itsupport@paygate.co.za</Email>
        <Address>
          <AddressLine />
          <AddressLine />
          <AddressLine />
          <Country>ZAF</Country>
        </Address>
      </Customer>
      <Address>
        <AddressLine />
        <AddressLine />
        <AddressLine />
        <Country>ZAF</Country>
      </Address>
    </BillingDetails>
  </Order>
  <UserDefinedFields xmlns="http://www.paygate.co.za/PayHOST">
    <key />
    <value />
  </UserDefinedFields>
</WebPaymentRequestType>
```

Any assistance you can offer would be appreciated.

**Comment by MenWhoRust** [comment]
From email comms with DPO SA Customer support

```
Thank you for contacting DPO South Africa.

The error you are receiving is due a recent rule put in place by our infrastructure team and it unfortunately has to be there for our PCI compliance.

We recently had to make changes to our firewall.
If the body of a POST message coming to us contains either localhost or 127.0.0.1, a firewall rule kicks in and blocks the request.

Please change the return URL you are passing us in the request in order to resolve the issue.

You will have to get around it by including an entry in your 'host' file that points to a different URL, for example: 127.0.0.1 dev.companyname #localhost bypassand use the 'dev.companyname' in place of 'localhost' in your return URL.

Please don't hesitate to contact us should you experience further issues.
```
